services:
  fepgc:
    image: fepgc
    container_name: fepgc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: develop
    ports:
      - 80:5173
    networks:
      - fe-network
      - be-network 
networks:
  fe-network:
    driver: bridge
    external: true
  be-network:
    driver: bridge
    external: true